name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pyinstaller opencv-python PyQt5 mediapipe tensorflow-cpu vosk sounddevice keyboard pyttsx3

    - name: Download Vosk Models
      run: |
        # Скачиваем русскую модель
        curl -L https://alphacephei.com/vosk/models/vosk-model-small-ru-0.22.zip -o ru.zip
        tar -xf ru.zip
        
        # Скачиваем английскую модель (и переименовываем папку под твой код)
        curl -L https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip -o en.zip
        tar -xf en.zip
        # В твоем коде указано имя "vosk-model-en-us-0.22-lgraph", переименуем для совместимости
        if (Test-Path "vosk-model-small-en-us-0.15") { Rename-Item "vosk-model-small-en-us-0.15" "vosk-model-en-us-0.22-lgraph" }

    - name: Build EXE
      run: |
        python -m PyInstaller --noconfirm --onedir --windowed --add-data "labels.txt;." --add-data "model.keras;." --add-data "vosk-model-small-ru-0.22;vosk-model-small-ru-0.22" --add-data "vosk-model-en-us-0.22-lgraph;vosk-model-en-us-0.22-lgraph" --collect-all mediapipe --collect-all vosk --collect-all cv2 --collect-all PyQt5 e2.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GestureOS-Windows-Build
        path: dist/
